# OS identification from: https://stackoverflow.com/questions/714100/os-detecting-makefile
OS := $(shell uname -s)

ifeq ($(OS), Darwin) 
  INCLUDE_PATH := /opt/homebrew/include
  LIB_PATH := /opt/homebrew/lib
  CC := gcc
endif
ifeq ($(OS), Linux) 
  INCLUDE_PATH := /util/criterion/include
  LIB_PATH := /util/criterion/lib/x86_64-linux-gnu
  CC := gcc
endif

CFLAGS := -g -Wall -O0 -fprofile-arcs -ftest-coverage -std=c11

schemeValidator.o: schemeValidator.c schemeValidator.h
	$(CC) $(CFLAGS) -c schemeValidator.c

schemeValidatorTests.o: schemeValidatorTests.c schemeValidator.h 
	$(CC) $(CFLAGS) -c -I $(INCLUDE_PATH) schemeValidatorTests.c

tests:  schemeValidator.o schemeValidatorTests.o
	$(CC) $(DEBUG) $(CFLAGS) -L $(LIB_PATH) -I $(INCLUDE_PATH) -o tests schemeValidator.o schemeValidatorTests.o -lcriterion -lgcov

.PHONY: clean info
clean:
	rm -rf tests *~ *.o *.xml *.gc?? *.dSYM 

info:
	@echo "User-targets:"
	@echo "\ttests - the executable for the Criterion tests"
	@echo "\tclean - remove Emacs autosave files and files generated by the compiler and gcov"
	@echo "\tinfo - print this message"
